#include "pih/model/deepseek_rank_serving_worker_loop.h"
#include <gtest/gtest.h>
namespace pih { namespace {
Sha256Digest root(){ return Sha256Digest::ParseHex("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef").value(); }
DeepSeekRankServingCommand command(){ DeepSeekRankServingCommand c; c.session={7,8,1,0,1,2,3,root()}; c.command_sequence=1;c.request_id=4;c.request_generation=5;c.plan={7,6,DeepSeekPlanPhase::kDecode,1,1};c.input_lease_identity=8;c.output_lease_identity=9;return c; }
class T final: public DeepSeekRankServingWorkerTransport { public: Result<std::optional<DeepSeekRankServingCommand>> receive() override { auto x=in;in.reset();return x;} Status send(const DeepSeekRankServingCompletion& c) override { ++sends; last=c; return send_status;} std::optional<DeepSeekRankServingCommand> in; DeepSeekRankServingCompletion last; Status send_status=Status::Ok(); int sends=0;};
class E final: public DeepSeekRankServingWorkerExecutor { public: Status start(const DeepSeekRankServingCommand& c) override { active=c;return Status::Ok();} Status cancel(const DeepSeekRankServingCommand&) override{return Status::Ok();} Result<std::optional<DeepSeekRankServingCompletion>> poll() override { if(!active)return std::optional<DeepSeekRankServingCompletion>{}; DeepSeekRankServingCompletion x; x.session=active->session;x.execution_command_sequence=active->command_sequence;x.request_id=active->request_id;x.request_generation=active->request_generation;x.plan=active->plan;x.output_lease_identity=active->output_lease_identity;active.reset();return std::optional<DeepSeekRankServingCompletion>(x);} std::optional<DeepSeekRankServingCommand> active;};
TEST(DeepSeekRankServingWorkerLoopTest, RetriesCompletionWithoutReexecuting){T t;E e; auto g=DeepSeekRankServingWorkerGate::Create(command().session).value();auto l=DeepSeekRankServingWorkerLoop::Create(std::move(g),t,e).value();t.in=command(); ASSERT_TRUE(l.advance().ok()); EXPECT_EQ(t.sends,0); t.send_status=Status::Unavailable("x"); EXPECT_EQ(l.advance().code(),StatusCode::kUnavailable); EXPECT_EQ(t.sends,1);t.send_status=Status::Ok();ASSERT_TRUE(l.advance().ok());EXPECT_EQ(t.sends,2);}
}}
