# Transfer actual CUDA translation units out of rank archives. The rank keeps
# host planners/validators and one capability dispatch table, never CUDA kernels.
if(NOT CMAKE_CUDA_ARCHITECTURES STREQUAL "103-real")
    message(FATAL_ERROR "V4.1 SM103 Pack requires exactly 103-real")
endif()
get_property(v41_targets DIRECTORY "${PROJECT_SOURCE_DIR}" PROPERTY BUILDSYSTEM_TARGETS)
set(PIH_V41_PACK_SOURCES)
foreach(v41_target IN LISTS v41_targets)
    if(NOT v41_target MATCHES "^pih_deepseek_v41_")
        continue()
    endif()
    get_target_property(v41_sources ${v41_target} SOURCES)
    set(v41_cuda ${v41_sources})
    list(FILTER v41_cuda INCLUDE REGEX "\\.cu$")
    if(NOT v41_cuda)
        continue()
    endif()
    list(APPEND PIH_V41_PACK_SOURCES ${v41_sources})
    list(FILTER v41_sources EXCLUDE REGEX "\\.cu$")
    if(v41_target STREQUAL "pih_deepseek_v41_sampling_cuda")
        set(v41_sources "${PROJECT_SOURCE_DIR}/plugins/model-deepseek-v41/kernel_binding.cpp")
    else()
        get_target_property(v41_links ${v41_target} LINK_LIBRARIES)
        target_link_libraries(${v41_target} PRIVATE pih_deepseek_v41_sampling_cuda)
        pih_assert_direct_link_allowlist(${v41_target} ${v41_links} pih_deepseek_v41_sampling_cuda)
    endif()
    set_property(TARGET ${v41_target} PROPERTY SOURCES ${v41_sources})
endforeach()
list(REMOVE_DUPLICATES PIH_V41_PACK_SOURCES)
if(NOT PIH_V41_PACK_SOURCES)
    message(FATAL_ERROR "V4.1 SM103 Pack has no native kernel sources")
endif()
