set(PIH_QWEN_KERNEL_ARCHITECTURES "89;90" CACHE STRING
    "Exact Qwen Kernel Pack architecture selection: 89, 90, or 89;90")
if(NOT PIH_QWEN_KERNEL_ARCHITECTURES MATCHES "^(89|90)(;(89|90))*$")
    message(FATAL_ERROR "Qwen Kernel Pack architectures must be a nonempty list containing only 89 and/or 90")
endif()
set(pih_qwen_unique_architectures ${PIH_QWEN_KERNEL_ARCHITECTURES})
list(LENGTH pih_qwen_unique_architectures pih_qwen_architecture_count)
list(REMOVE_DUPLICATES pih_qwen_unique_architectures)
list(LENGTH pih_qwen_unique_architectures pih_qwen_unique_count)
if(NOT pih_qwen_architecture_count EQUAL pih_qwen_unique_count)
    message(FATAL_ERROR "Duplicate Qwen Kernel Pack architecture")
endif()
unset(pih_qwen_unique_architectures)
unset(pih_qwen_architecture_count)
unset(pih_qwen_unique_count)
