# Offline sealing only. This script never loads a plugin or starts a worker.
if(NOT CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
    message(FATAL_ERROR "Native V4.1 sealing requires Linux ELF artifacts")
endif()
if(NOT IS_ABSOLUTE "${BUNDLE}" OR NOT IS_DIRECTORY "${BUNDLE}" OR IS_SYMLINK "${BUNDLE}"
   OR BUNDLE MATCHES "[\\\"\\\\\n\r]")
    message(FATAL_ERROR "Use an absolute existing bundle directory without links or JSON escapes")
endif()
file(REAL_PATH "${BUNDLE}" bundle_real)
if(NOT bundle_real STREQUAL BUNDLE OR
   NOT IS_DIRECTORY "${BUNDLE}/lib" OR IS_SYMLINK "${BUNDLE}/lib" OR
   NOT IS_DIRECTORY "${BUNDLE}/bin" OR IS_SYMLINK "${BUNDLE}/bin")
    message(FATAL_ERROR "Bundle path and bin/lib directories must be canonical and link-free")
endif()
function(binary relative result)
    set(path "${BUNDLE}/${relative}")
    if(NOT EXISTS "${path}" OR IS_DIRECTORY "${path}" OR IS_SYMLINK "${path}")
        message(FATAL_ERROR "Missing regular bundle artifact: ${relative}")
    endif()
    file(READ "${path}" magic OFFSET 0 LIMIT 4 HEX)
    if(NOT magic STREQUAL "7f454c46")
        message(FATAL_ERROR "Not an ELF artifact: ${relative}")
    endif()
    file(SHA256 "${path}" digest)
    set(${result} "${digest}" PARENT_SCOPE)
endfunction()
function(publish path bytes)
    if(EXISTS "${path}" OR IS_SYMLINK "${path}")
        message(FATAL_ERROR "Refusing to overwrite existing lock: ${path}")
    endif()
    file(WRITE "${path}" "${bytes}")
    file(CHMOD "${path}" PERMISSIONS OWNER_READ GROUP_READ WORLD_READ)
    file(SHA256 "${path}" digest)
    message(STATUS "Sealed ${path}: ${digest}")
endfunction()
if(MODE STREQUAL "rank")
    binary("lib/pih_plugin_platform_linux.so" platform)
    binary("lib/pih_plugin_backend_nvidia_cuda.so" backend)
    binary("lib/pih_plugin_transport_nccl.so" transport)
    binary("lib/pih_kernels_deepseek_v41_sm103.so" kernels)
    binary("bin/pih-v41-rank-worker" worker)
    binary("bin/pih-v41-nccl-bootstrap" helper)
    set(bytes "{\"schema\":\"pih.development-lock.v1\",\"support_status\":\"unsupported\",\"kernel_packs\":[{\"pack_id\":\"pih.kernels.deepseek-v41.sm103\",\"pack_version\":\"1.0.0\",\"pack_abi\":\"pih.deepseek-v41-sm103-kernels.v1\",\"architecture\":\"sm103\",\"binary\":\"lib/pih_kernels_deepseek_v41_sm103.so\",\"binary_sha256_hex\":\"${kernels}\"}],\"plugins\":[{\"plugin_id\":\"pih.platform.linux\",\"plugin_version\":\"1.0.0\",\"entrypoint\":\"lib/pih_plugin_platform_linux.so\",\"entrypoint_sha256_hex\":\"${platform}\"},{\"plugin_id\":\"pih.backend.nvidia-cuda\",\"plugin_version\":\"1.0.0\",\"entrypoint\":\"lib/pih_plugin_backend_nvidia_cuda.so\",\"entrypoint_sha256_hex\":\"${backend}\"},{\"plugin_id\":\"pih.transport.nccl\",\"plugin_version\":\"1.0.0\",\"entrypoint\":\"lib/pih_plugin_transport_nccl.so\",\"entrypoint_sha256_hex\":\"${transport}\"}],\"capabilities\":[")
    foreach(kind async memory resources runtime)
        string(APPEND bytes "{\"capability_id\":\"device.cuda-${kind}.v1\",\"provider_id\":\"pih.backend.nvidia-cuda\",\"contract_id\":\"pih.device.cuda-${kind}.v1\",\"threading_model\":2,\"scope\":1,\"cardinality\":1},")
    endforeach()
    string(APPEND bytes "{\"capability_id\":\"pih.kernels.deepseek-v41.sm103\",\"provider_id\":\"pih.kernels.deepseek-v41.sm103\",\"contract_id\":\"pih.deepseek-v41-sm103-kernels.v1\",\"threading_model\":3,\"scope\":2,\"cardinality\":1},{\"capability_id\":\"platform.linux.v1\",\"provider_id\":\"pih.platform.linux\",\"contract_id\":\"pih.platform.linux.v1\",\"threading_model\":2,\"scope\":1,\"cardinality\":1},{\"capability_id\":\"transport.collective.v1\",\"provider_id\":\"pih.transport.nccl\",\"contract_id\":\"pih.transport.collective.v1\",\"threading_model\":2,\"scope\":1,\"cardinality\":1}]}")
    publish("${BUNDLE}/v41-rank.lock" "${bytes}")
    message(STATUS "Supervisor worker SHA256: ${worker}; helper SHA256: ${helper}")
elseif(MODE STREQUAL "service")
    if(NOT IS_ABSOLUTE "${CONFIG}" OR IS_SYMLINK "${CONFIG}" OR
       IS_DIRECTORY "${CONFIG}" OR CONFIG MATCHES "[\\\"\\\\\n\r]"
       OR NOT EXISTS "${CONFIG}")
        message(FATAL_ERROR "CONFIG must be an absolute regular configuration path")
    endif()
    file(REAL_PATH "${CONFIG}" config_real)
    if(NOT config_real STREQUAL CONFIG)
        message(FATAL_ERROR "CONFIG path must be canonical and link-free")
    endif()
    # The path is embedded in a JSON Lock below. A POSIX filename may contain
    # control bytes even though the native configuration path contract forbids
    # them; reject such paths before publishing an invalid or ambiguous Lock.
    string(HEX "${CONFIG}" config_path_hex)
    string(REGEX MATCHALL ".." config_path_bytes "${config_path_hex}")
    foreach(config_path_byte IN LISTS config_path_bytes)
        math(EXPR config_path_value "0x${config_path_byte}")
        if(config_path_value LESS 32 OR config_path_value EQUAL 127)
            message(FATAL_ERROR "CONFIG path contains a control character")
        endif()
    endforeach()
    file(SIZE "${CONFIG}" config_size)
    if(config_size LESS 1 OR config_size GREATER 2097152)
        message(FATAL_ERROR "Supervisor configuration exceeds the 2 MiB sealing limit")
    endif()
    string(LENGTH "${CONFIG_SHA256}" length)
    file(SHA256 "${CONFIG}" actual)
    if(NOT length EQUAL 64 OR NOT CONFIG_SHA256 MATCHES "^[0-9a-f]+$" OR NOT actual STREQUAL CONFIG_SHA256)
        message(FATAL_ERROR "Configuration differs from independently trusted SHA256")
    endif()
    file(READ "${CONFIG}" config LIMIT 2097153)
    string(JSON schema GET "${config}" schema)
    if(NOT schema STREQUAL "pih.deepseek-v41.supervisor.v1")
        message(FATAL_ERROR "Configuration schema invalid")
    endif()
    string(JSON major GET "${config}" model sm_major)
    string(JSON minor GET "${config}" model sm_minor)
    if(NOT major EQUAL 10 OR NOT minor EQUAL 3)
        message(FATAL_ERROR "V4.1 service requires SM103 configuration")
    endif()
    string(JSON rank_lock GET "${config}" model plugin_lock)
    string(JSON rank_digest GET "${config}" model plugin_lock_sha256)
    if(NOT rank_lock STREQUAL "${BUNDLE}/v41-rank.lock" OR IS_SYMLINK "${rank_lock}")
        message(FATAL_ERROR "Configuration must use this bundle's sealed rank lock")
    endif()
    file(SHA256 "${rank_lock}" actual)
    if(NOT actual STREQUAL rank_digest)
        message(FATAL_ERROR "Configuration rank lock digest mismatch")
    endif()
    foreach(role worker helper)
        if(role STREQUAL "worker")
            set(name pih-v41-rank-worker)
        else()
            set(name pih-v41-nccl-bootstrap)
        endif()
        binary("bin/${name}" actual)
        string(JSON path GET "${config}" ${role} path)
        string(JSON expected GET "${config}" ${role} sha256)
        if(NOT path STREQUAL "${BUNDLE}/bin/${name}" OR NOT expected STREQUAL actual)
            message(FATAL_ERROR "Configuration ${role} differs from this bundle")
        endif()
    endforeach()
    string(JSON epoch GET "${config}" request identity epoch)
    binary("lib/pih_plugin_model_deepseek_v41.so" model)
    binary("lib/pih_plugin_surface_text_http.so" surface)
    set(bytes "{\"schema\":\"pih.development-lock.v1\",\"support_status\":\"unsupported\",\"kernel_packs\":[],\"plugins\":[{\"plugin_id\":\"pih.model.deepseek-v41\",\"plugin_version\":\"1.0.0\",\"entrypoint\":\"lib/pih_plugin_model_deepseek_v41.so\",\"entrypoint_sha256_hex\":\"${model}\"},{\"plugin_id\":\"pih.surface.text-http\",\"plugin_version\":\"1.0.0\",\"entrypoint\":\"lib/pih_plugin_surface_text_http.so\",\"entrypoint_sha256_hex\":\"${surface}\"}],\"capabilities\":[{\"capability_id\":\"inference.text.v2\",\"provider_id\":\"pih.model.deepseek-v41\",\"contract_id\":\"pih.inference.text.v2\",\"threading_model\":2,\"scope\":2,\"cardinality\":1},{\"capability_id\":\"surface.text-http.v2\",\"provider_id\":\"pih.surface.text-http\",\"contract_id\":\"pih.surface.text-http.v2\",\"threading_model\":2,\"scope\":2,\"cardinality\":1}],\"engine\":{\"capability_id\":\"inference.text.v2\",\"contract_id\":\"pih.inference.text.v2\",\"activation_epoch\":${epoch},\"configuration\":{\"supervisor_configuration\":\"${CONFIG}\",\"supervisor_configuration_sha256\":\"${CONFIG_SHA256}\"},\"smoke_http_body\":{}}}")
    publish("${BUNDLE}/v41-service.lock" "${bytes}")
else()
    message(FATAL_ERROR "MODE must be rank or service")
endif()
