set(receipt "${CMAKE_INSTALL_PREFIX}/NATIVE-INSTALL.json")
if(EXISTS "${receipt}" OR IS_SYMLINK "${receipt}")
    message(FATAL_ERROR "Use a new release installation directory; receipt already exists")
endif()
set(entries "")
list(REMOVE_DUPLICATES CMAKE_INSTALL_MANIFEST_FILES)
list(SORT CMAKE_INSTALL_MANIFEST_FILES)
foreach(path IN LISTS CMAKE_INSTALL_MANIFEST_FILES)
    file(RELATIVE_PATH relative "${CMAKE_INSTALL_PREFIX}" "${path}")
    if(relative MATCHES "^\\.\\." OR relative MATCHES "[\"\\\\\n\r]" OR IS_SYMLINK "${path}")
        message(FATAL_ERROR "Invalid release member: ${relative}")
    endif()
    file(SHA256 "${path}" digest)
    file(SIZE "${path}" bytes)
    if(NOT entries STREQUAL "")
        string(APPEND entries ",\n")
    endif()
    string(APPEND entries "    {\"path\":\"${relative}\",\"sha256\":\"${digest}\",\"bytes\":${bytes}}")
endforeach()
file(WRITE "${receipt}" "{\"schema\":\"pih.native-install.v1\",\"files\":[\n${entries}\n]}\n")
